name: Validate codebase (build, lint, test)

on:
  workflow_call:

jobs:
  built_lint_test:
    name: Build, test and lint the codebase
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js environment with yarn cache
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Setup Turborepo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.ref_name }}-${{ github.event.pull_request.head.sha }}
          restore-keys: |
            turbo-${{ github.ref_name }}-
            turbo-

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build --cache-dir=".turbo"

      - name: Lint
        run: yarn lint --cache-dir=".turbo"

      - name: Test
        run: yarn test --cache-dir=".turbo"
