name: Single deployment step

on:
  workflow_call:
    inputs:
      matrix-row:
        required: true
        type: string

jobs:
 deploy:
    name: Deploy
    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJSON(inputs.matrix-row) }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout_backend
        name: Checkout Backend
        uses: actions/checkout@v2

      - name: Setup Node.js environment with yarn cache
        uses: actions/setup-node@v2
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.ref_name }}-${{ github.event.pull_request.head.sha }}
          restore-keys: |
            turbo-${{ github.ref_name }}-
            turbo-

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build --cache-dir=".turbo"
        
      - name: Deploy
        shell: bash
        run: |
          echo "deployed";